# Generated by Django 3.2.6 on 2023-12-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbaseapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='billing',
            name='is_paid',
            field=models.BooleanField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='billing',
            name='payment_intent_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
