# Generated by Django 3.2.6 on 2023-12-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbaseapp', '0002_edit_billing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='billing',
            name='status',
            field=models.CharField(default='paid', max_length=50),
        ),
    ]
