# Generated by Django 3.2.6 on 2023-12-03 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbaseapp', '0003_edit_billing_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('plan', models.CharField(default='monthly', max_length=50)),
                ('duration', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
